id: A027C264A
base_file: fAB4F.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 18:01:12.732905
  last_modified_at: 2022-06-19 18:01:12.732910
