id: A027C264A
base_file: fA3F8.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 18:01:12.730443
  last_modified_at: 2022-06-19 18:01:12.730455
